/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RadarRouteImport } from './routes/radar'
import { Route as GamesRouteImport } from './routes/games'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesPalmRouteImport } from './routes/games.palm'
import { Route as GamesLeaderboardRouteImport } from './routes/games.leaderboard'
import { Route as ExploreVoiceRouteImport } from './routes/explore.voice'
import { Route as ExploreVideoRouteImport } from './routes/explore.video'
import { Route as ExploreTreeholeRouteImport } from './routes/explore.treehole'

const RadarRoute = RadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesPalmRoute = GamesPalmRouteImport.update({
  id: '/palm',
  path: '/palm',
  getParentRoute: () => GamesRoute,
} as any)
const GamesLeaderboardRoute = GamesLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => GamesRoute,
} as any)
const ExploreVoiceRoute = ExploreVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreVideoRoute = ExploreVideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => ExploreRoute,
} as any)
const ExploreTreeholeRoute = ExploreTreeholeRouteImport.update({
  id: '/treehole',
  path: '/treehole',
  getParentRoute: () => ExploreRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/explore': typeof ExploreRouteWithChildren
  '/games': typeof GamesRouteWithChildren
  '/radar': typeof RadarRoute
  '/explore/treehole': typeof ExploreTreeholeRoute
  '/explore/video': typeof ExploreVideoRoute
  '/explore/voice': typeof ExploreVoiceRoute
  '/games/leaderboard': typeof GamesLeaderboardRoute
  '/games/palm': typeof GamesPalmRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/explore': typeof ExploreRouteWithChildren
  '/games': typeof GamesRouteWithChildren
  '/radar': typeof RadarRoute
  '/explore/treehole': typeof ExploreTreeholeRoute
  '/explore/video': typeof ExploreVideoRoute
  '/explore/voice': typeof ExploreVoiceRoute
  '/games/leaderboard': typeof GamesLeaderboardRoute
  '/games/palm': typeof GamesPalmRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/explore': typeof ExploreRouteWithChildren
  '/games': typeof GamesRouteWithChildren
  '/radar': typeof RadarRoute
  '/explore/treehole': typeof ExploreTreeholeRoute
  '/explore/video': typeof ExploreVideoRoute
  '/explore/voice': typeof ExploreVoiceRoute
  '/games/leaderboard': typeof GamesLeaderboardRoute
  '/games/palm': typeof GamesPalmRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/discover'
    | '/explore'
    | '/games'
    | '/radar'
    | '/explore/treehole'
    | '/explore/video'
    | '/explore/voice'
    | '/games/leaderboard'
    | '/games/palm'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discover'
    | '/explore'
    | '/games'
    | '/radar'
    | '/explore/treehole'
    | '/explore/video'
    | '/explore/voice'
    | '/games/leaderboard'
    | '/games/palm'
  id:
    | '__root__'
    | '/'
    | '/discover'
    | '/explore'
    | '/games'
    | '/radar'
    | '/explore/treehole'
    | '/explore/video'
    | '/explore/voice'
    | '/games/leaderboard'
    | '/games/palm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiscoverRoute: typeof DiscoverRoute
  ExploreRoute: typeof ExploreRouteWithChildren
  GamesRoute: typeof GamesRouteWithChildren
  RadarRoute: typeof RadarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/radar': {
      id: '/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof RadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/palm': {
      id: '/games/palm'
      path: '/palm'
      fullPath: '/games/palm'
      preLoaderRoute: typeof GamesPalmRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/leaderboard': {
      id: '/games/leaderboard'
      path: '/leaderboard'
      fullPath: '/games/leaderboard'
      preLoaderRoute: typeof GamesLeaderboardRouteImport
      parentRoute: typeof GamesRoute
    }
    '/explore/voice': {
      id: '/explore/voice'
      path: '/voice'
      fullPath: '/explore/voice'
      preLoaderRoute: typeof ExploreVoiceRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/explore/video': {
      id: '/explore/video'
      path: '/video'
      fullPath: '/explore/video'
      preLoaderRoute: typeof ExploreVideoRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/explore/treehole': {
      id: '/explore/treehole'
      path: '/treehole'
      fullPath: '/explore/treehole'
      preLoaderRoute: typeof ExploreTreeholeRouteImport
      parentRoute: typeof ExploreRoute
    }
  }
}

interface ExploreRouteChildren {
  ExploreTreeholeRoute: typeof ExploreTreeholeRoute
  ExploreVideoRoute: typeof ExploreVideoRoute
  ExploreVoiceRoute: typeof ExploreVoiceRoute
}

const ExploreRouteChildren: ExploreRouteChildren = {
  ExploreTreeholeRoute: ExploreTreeholeRoute,
  ExploreVideoRoute: ExploreVideoRoute,
  ExploreVoiceRoute: ExploreVoiceRoute,
}

const ExploreRouteWithChildren =
  ExploreRoute._addFileChildren(ExploreRouteChildren)

interface GamesRouteChildren {
  GamesLeaderboardRoute: typeof GamesLeaderboardRoute
  GamesPalmRoute: typeof GamesPalmRoute
}

const GamesRouteChildren: GamesRouteChildren = {
  GamesLeaderboardRoute: GamesLeaderboardRoute,
  GamesPalmRoute: GamesPalmRoute,
}

const GamesRouteWithChildren = GamesRoute._addFileChildren(GamesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiscoverRoute: DiscoverRoute,
  ExploreRoute: ExploreRouteWithChildren,
  GamesRoute: GamesRouteWithChildren,
  RadarRoute: RadarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
